alias c="clear"
alias cl="clear;ls"
alias cll="clear;ls -la"

alias search="apt search"
alias show="apt show"
alias install="sudo apt install"
alias update="sudo apt update"
alias upgrade="sudo apt upgrade"
alias upgradable="sudo apt list --upgradable"
alias remove="sudo apt remove"
alias autoremove="sudo apt autoremove"
alias autoclean="sudo apt autoclean"

alias up="cd .."
alias upup="cd ../.."
alias up2="cd ../.."
alias up3="cd ../../.."
alias up4="cd ../../../.."
alias up5="cd ../../../../.."
alias upll="cd ..;ls -la"
alias upcl="cd ..;clear;ls"
alias upcll="cd ..;clear;ls -la"

alias cdl="cd; ls"
alias cdll="cd; ls -la"
alias cdc="cd; clear"
alias cdcl="cd; clear; ls"
alias cdcll="cd; clear; ls -la"

alias restart="shutdown -r now"
alias shutdown="shutdown now"
